package me.itangqi.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import me.itangqi.greendao.HomeRecommendEntity;

import me.itangqi.greendao.HomeRecommendEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig homeRecommendEntityDaoConfig;

    private final HomeRecommendEntityDao homeRecommendEntityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        homeRecommendEntityDaoConfig = daoConfigMap.get(HomeRecommendEntityDao.class).clone();
        homeRecommendEntityDaoConfig.initIdentityScope(type);

        homeRecommendEntityDao = new HomeRecommendEntityDao(homeRecommendEntityDaoConfig, this);

        registerDao(HomeRecommendEntity.class, homeRecommendEntityDao);
    }
    
    public void clear() {
        homeRecommendEntityDaoConfig.getIdentityScope().clear();
    }

    public HomeRecommendEntityDao getHomeRecommendEntityDao() {
        return homeRecommendEntityDao;
    }

}
