package me.itangqi.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table t_home_recommend.
 */
public class HomeRecommendEntity {

    private Long vId;
    private Integer subjectId;
    private String timeLength;
    private String channelTitle;
    private String createdTime;
    private String description;
    private String team;
    private Integer sort;
    private String title;
    private String videoUrl;
    private String size;
    private String previewImageUrl;
    private Boolean recommend;
    private Integer channelId;
    private Boolean studyrecord;
    private Boolean collect;

    public HomeRecommendEntity() {
    }

    public HomeRecommendEntity(Long vId) {
        this.vId = vId;
    }

    public HomeRecommendEntity(Long vId, Integer subjectId, String timeLength, String channelTitle, String createdTime, String description, String team, Integer sort, String title, String videoUrl, String size, String previewImageUrl, Boolean recommend, Integer channelId, Boolean studyrecord, Boolean collect) {
        this.vId = vId;
        this.subjectId = subjectId;
        this.timeLength = timeLength;
        this.channelTitle = channelTitle;
        this.createdTime = createdTime;
        this.description = description;
        this.team = team;
        this.sort = sort;
        this.title = title;
        this.videoUrl = videoUrl;
        this.size = size;
        this.previewImageUrl = previewImageUrl;
        this.recommend = recommend;
        this.channelId = channelId;
        this.studyrecord = studyrecord;
        this.collect = collect;
    }

    public Long getVId() {
        return vId;
    }

    public void setVId(Long vId) {
        this.vId = vId;
    }

    public Integer getSubjectId() {
        return subjectId;
    }

    public void setSubjectId(Integer subjectId) {
        this.subjectId = subjectId;
    }

    public String getTimeLength() {
        return timeLength;
    }

    public void setTimeLength(String timeLength) {
        this.timeLength = timeLength;
    }

    public String getChannelTitle() {
        return channelTitle;
    }

    public void setChannelTitle(String channelTitle) {
        this.channelTitle = channelTitle;
    }

    public String getCreatedTime() {
        return createdTime;
    }

    public void setCreatedTime(String createdTime) {
        this.createdTime = createdTime;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getTeam() {
        return team;
    }

    public void setTeam(String team) {
        this.team = team;
    }

    public Integer getSort() {
        return sort;
    }

    public void setSort(Integer sort) {
        this.sort = sort;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getVideoUrl() {
        return videoUrl;
    }

    public void setVideoUrl(String videoUrl) {
        this.videoUrl = videoUrl;
    }

    public String getSize() {
        return size;
    }

    public void setSize(String size) {
        this.size = size;
    }

    public String getPreviewImageUrl() {
        return previewImageUrl;
    }

    public void setPreviewImageUrl(String previewImageUrl) {
        this.previewImageUrl = previewImageUrl;
    }

    public Boolean getRecommend() {
        return recommend;
    }

    public void setRecommend(Boolean recommend) {
        this.recommend = recommend;
    }

    public Integer getChannelId() {
        return channelId;
    }

    public void setChannelId(Integer channelId) {
        this.channelId = channelId;
    }

    public Boolean getStudyrecord() {
        return studyrecord;
    }

    public void setStudyrecord(Boolean studyrecord) {
        this.studyrecord = studyrecord;
    }

    public Boolean getCollect() {
        return collect;
    }

    public void setCollect(Boolean collect) {
        this.collect = collect;
    }

}
